
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-05
owner: ucsb-cs156-f24
repo_name: team01-f24-05
pull_requests: [{"author":{"id":"U_kgDOB1QJQw","is_bot":false,"login":"RyanZanone","name":""},"headRefName":"ryanzanone-HelpRequest-delete","number":48,"title":"Added DELETE by id functionality to HelpRequest db","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/48"},{"author":{"id":"U_kgDOB1QJQw","is_bot":false,"login":"RyanZanone","name":""},"headRefName":"ryanzanone-HelpRequest-addGetPost","number":47,"title":"Added GET (all) and POST functionality HelpRequest db","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/47"}]
