
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-05
owner: ucsb-cs156-f24
repo_name: team01-f24-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjI5MzkxNjA1","is_bot":false,"login":"17acastelein","name":""},"headRefName":"17acastelein","number":54,"title":"added database files and chromatic connection","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/54"},{"author":{"id":"U_kgDOB1P9DQ","is_bot":false,"login":"bgggggh","name":""},"headRefName":"bg-MenuItemReview-put","number":53,"title":"Added PUT(edit) to MenuItemReview","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/53"},{"author":{"id":"U_kgDOB1P9DQ","is_bot":false,"login":"bgggggh","name":""},"headRefName":"bg-MenuItemReview-delete","number":52,"title":"Baige menu item review delete","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/52"},{"author":{"id":"U_kgDOB1P9DQ","is_bot":false,"login":"bgggggh","name":""},"headRefName":"bg-MenuItemReview-create-db","number":51,"title":"Added GET(show) to MenuItemReview, revised Entity&Migration for Swagger","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/51"},{"author":{"id":"U_kgDOB1QJQw","is_bot":false,"login":"RyanZanone","name":""},"headRefName":"ryanzanone-HelpRequest-getShow","number":50,"title":"Added GET (show) functionality to HelpRequest db","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/50"},{"author":{"id":"U_kgDOB1QJQw","is_bot":false,"login":"RyanZanone","name":""},"headRefName":"ryanzanone-HelpRequest-put","number":49,"title":"Added PUT (edit) functionality for HelpRequest db","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/49"},{"author":{"id":"U_kgDOB1QJQw","is_bot":false,"login":"RyanZanone","name":""},"headRefName":"ryanzanone-HelpRequest-delete","number":48,"title":"Added DELETE by id functionality to HelpRequest db","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/48"},{"author":{"id":"U_kgDOB1QJQw","is_bot":false,"login":"RyanZanone","name":""},"headRefName":"ryanzanone-HelpRequest-addGetPost","number":47,"title":"Added GET (all) and POST functionality HelpRequest db","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/47"}]
