
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-05
owner: ucsb-cs156-f24
repo_name: team01-f24-05
pull_requests: [{"author":{"id":"U_kgDOB1P9DQ","is_bot":false,"login":"bgggggh","name":""},"headRefName":"bg-MenuItemReview-create-db","number":46,"title":"entity,repo,migration","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/46"},{"author":{"id":"MDQ6VXNlcjczOTIyMDEz","is_bot":false,"login":"basperheim1","name":""},"headRefName":"basperheim1-Articles-create-db","number":45,"title":"Basperheim1 articles create db","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/45"}]
