
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-05
owner: ucsb-cs156-f24
repo_name: team01-f24-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjczOTIyMDEz","is_bot":false,"login":"basperheim1","name":""},"headRefName":"get-singular-articles","number":61,"title":"Add get endpoint for Articles (singular)","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/61"},{"author":{"id":"MDQ6VXNlcjI1MjgzOTIx","is_bot":false,"login":"ishanjainofficial","name":"Ishan Jain"},"headRefName":"Ishan-DeletePutGet","number":60,"title":"Ishan delete put get","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/60"},{"author":{"id":"MDQ6VXNlcjczOTIyMDEz","is_bot":false,"login":"basperheim1","name":""},"headRefName":"basperheim1-Articles-get-singular","number":58,"title":"Get endpoint (singular) for Articles table ","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/58"},{"author":{"id":"MDQ6VXNlcjczOTIyMDEz","is_bot":false,"login":"basperheim1","name":""},"headRefName":"basperheim1-Articles-post-get","number":56,"title":"Articles get / post endpoint ","url":"https://github.com/ucsb-cs156-f24/team01-f24-05/pull/56"}]
